name: Java CI with Maven

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - .github/project.yml
      - "**.xml"
      - "src/**"
      - "ide-config"
  pull_request:
    paths:
      - "**.xml"
      - "src/**"
      - "ide-config"

env:
  MAVEN_VERIFY: "-B --no-transfer-progress formatter:validate verify"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      make_release: ${{ steps.filter.outputs.project }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        id: mvn-build
        run: |
          ./mvnw ${MAVEN_VERIFY}

      - uses: dorny/paths-filter@v2
        if: ${{ github.ref == 'refs/heads/main'}}
        id: filter
        with:
          filters: |
            project:
              - '.github/project.yml'
            
  update-snapshot:
    # Only run for successful build of the main branch
    if: ${{ github.ref == 'refs/heads/main' }} 
    needs: build
    uses: ./.github/workflows/antifreeze.yml
    secrets: inherit

