name: Java CI with Maven

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - .github/project.yml
      - "**.xml"
      - "src/**"
      - "ide-config"
  pull_request:
    paths:
      - "**.xml"
      - "src/**"
      - "ide-config"

env:
  MAVEN_VERIFY: "-B --no-transfer-progress formatter:validate verify"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        id: mvn-build
        run: |
          ./mvnw ${MAVEN_VERIFY}

      - name: Delete Local Artifacts From Maven repo
        shell: bash
        run: rm -r ~/.m2/repository/dev/ebullient

  update-snapshot:
    # Only run for successful build of the main branch
    needs: build
    uses: ./.github/workflows/antifreeze.yml
    secrets: inherit
